### PR TITLE
Use Wayland by default, fallback to X11

### LINKED ISSUE #4: Wayland support
The Vikunja flatpak is not configured to support Wayland (which is now becoming default in many systems).
Instead, when run in a Wayland enviroment, the flatpak still runs in XWayland.

Suggested:
a) It should run in Wayland and fall back to X (as many flatpaks now do)
b) Care should be taken to ensure the icon displays in Wayland (ensuring the correct 'appid' is set and it matches the first part of the .desktop file name.

### PR DESCRIPTION
**Pull request by RaptaG**
Fallbacks only if Wayland is not present.

Fixes #4

### CODE REVIEW

**Comment by RaptaG** [comment]
Now, I'll test it on my machine and if everything works flawlessly I'll merge it

**Comment by RaptaG** [comment]
There is a problem apparently:

```
[2:1105/130307.652555:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[2:1105/130307.652566:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.
```

**Comment by RaptaG** [comment]
After some research I found out that it could an issue of the application. @kolaente, does the app rely on `$DISPLAY` for the display protocol generally?

**Comment by kolaente** [comment]
> does the app rely on $DISPLAY for the display protocol generally?

Not explicitely, maybe Electron uses it?

**Comment by RaptaG** [comment]
> Not explicitely, maybe Electron uses it?

Idk man, I can't seem to find the root of the cause

I'll dive deeper into it soon though

**Comment by RaptaG** [comment]
@Minionflo could you assist me here on this PR?

**Comment by Minionflo** [comment]
does the base vikunja app support wayland?

**Comment by minionflo** [comment]
the flatpak documentation says: 

> Native wayland support in electron is experimental and often unstable. It is advised to stick with the X11 and Xwayland configuration above as the default.

should we still use wayland?

**Comment by minionflo** [comment]
I have a working commit but i dont have the permission to push it to the wayland branch.

**Comment by RaptaG** [comment]
> I have a working commit but i dont have the permission to push it to the wayland branch.

Running wayland? Open up a PR targeting the wayland branch and I will approve it!

**Comment by RaptaG** [comment]
> the flatpak documentation says: 
> 
> > Native wayland support in electron is experimental and often unstable. It is advised to stick with the X11 and Xwayland configuration above as the default.
> 
> should we still use wayland?

I am kinda sure it is outdated, many Electron Flatpaks run under Wayland (see Webcord)

**Comment by minionflo** [comment]
> > I have a working commit but i dont have the permission to push it to the wayland branch.
> 
> Running wayland? Open up a PR targeting the wayland branch and I will approve it!

done, see #15

**Comment by RaptaG** [comment]
@kolaente @Minionflo should be ready now

**Comment by RaptaG** [comment]
Big shout-out to @Minionflo for helping out!

**Comment by RaptaG** [comment]
@kolaente I am merging it, it should work as intended now

**Comment by kolaente** [comment]
LGTM!

**Pull request merged**
