### PR TITLE
added WMClass to desktop file

### LINKED ISSUE #10: Desktop file is missing the WMClass attribute
that causes 
image
if i click on the Vikunja icon

### PR DESCRIPTION
**Pull request by minionflo**
fixes #10

### CODE REVIEW

**Comment by RaptaG** [comment]
Thanks a lot for the contribution! Let me know if you need any help with getting it to compile or with testing it!

**Comment by minionflo** [comment]
it compiles and runs fine on my maschine. any idea why the build fails on here?

**Comment by kolaente** [comment]
The CI reports this error:

```
{
    "errors": [
        "appstream-failed-validation",
        "appstream-missing-developer-name"
    ],
    "appstream": [
        "W: io.vikunja.Vikunja:24: screenshot-default-missing"
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}

**Comment by minionflo** [comment]
any idea what the error means? Its my first time build with flatpak

**Comment by minionflo** [comment]
it seems like flatpak change some things which broke the auto builder. Im gonna open a seperate pr for fixing that

**Comment by minionflo** [comment]
i broke my branch stuff...

**Pull request closed without merging**
